### PR TITLE
Adding DateTimeQuestion class and test; updating entity type and context enums

### PR DESCRIPTION
**Pull request by ssciolla**
This PR adds a new class and test for DateTimeQuestion (`DateTimeQuestion.java` and `DateTimeQuestionTest.java`). In addition, new entries were added to the `EntityType` and `CaliperJsonldContext` enums to account for the new entity and the Survey Profile.

### CODE REVIEW

**Comment by ssciolla** [comment]
See newest commit. When (and how) do we want to move `v1p1` tests (including those I wrote previously) over to `v1p2`? The `v1p1` tests I wrote used a `JsonldStringContext.getDefault()` method to set the context.

**Comment by arwhyte** [comment]
Use context/CaliperJsonldContext enums instead for context value.  Update current test.  I will issue a PR that retires use of the config jsonld value.

**Comment by arwhyte** [comment]
I'm going to remove the JsonldStringContext getDefault() method.

**Comment by ssciolla** [comment]
I believe I am using the context/CaliperJsonldContext enum, as you suggest, in my latest commit: [94dc976](]https://github.com/IMSGlobal/caliper-java/pull/394/commits/94dc97621fe6ca7c365cd65b370d3e21911e22f7). I used the `getDefault()` method in the other tests I wrote. Do you want me to fix those now?

**Comment by arwhyte** [comment]
No, I am fixing them.  Give me ~ 15 minutes.

**Comment by arwhyte** [comment]
@ssciolla -- I expected your PR would involve merge conflicts following my latest merge.  See if you can resolve them.  Otherwise, I'll show you how to resolve them tomorrow.

**Comment by ssciolla** [comment]
@arwhyte It looks like I was able to resolve the merge conflict, and after modifying the context enum class name, I was able to get the test to pass.

**Pull request merged**
